# INSTRUÇÃO PRÁTICA - IP-P007
## Revisam e consolidaçao do conteúdo de __Pandas__ avançado.

### __Exercício 1: Carregando e analisando um DataSet__

Dados de estações metereologicas por ano: [Instituto Nacional de Meteorologia](https://portal.inmet.gov.br/dadoshistoricos). 
1. Download de dados de 2003, 2013 e 2023 da estação Salvador.
2. Carregando e analizando dados das três estações em ``DataFrame``s separados.

In [1]:
import pandas as pd

# carregando os aquivos csv
estacao_ssa_2003 = pd.read_csv('datasets/estacao_Salvador_2003.csv', sep=";", header=8, encoding='latin-1')
estacao_ssa_2013 = pd.read_csv('datasets/estacao_Salvador_2013.csv', sep=",", header=8, encoding='utf-8')
estacao_ssa_2023 = pd.read_csv('datasets/estacao_Salvador_2023.csv', sep=";", header=8, encoding='latin-1')

In [2]:
# estacao em 2003
estacao_ssa_2003.info()
estacao_ssa_2003.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 20 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   DATA (YYYY-MM-DD)                                      8760 non-null   object
 1   HORA (UTC)                                             8760 non-null   object
 2   PRECIPITAÇÃO TOTAL, HORÁRIO (mm)                       8760 non-null   object
 3   PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)  8760 non-null   object
 4   PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)        8760 non-null   object
 5   PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)       8760 non-null   object
 6   RADIACAO GLOBAL (KJ/m²)                                8760 non-null   int64
 7   TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)           8760 non-null   object
 8   TEMPERATURA DO PONTO DE ORVALHO (°C)                   8760 non-null   object
 9   TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)             8760 non-null   object
 10  TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)             8760 non-null   object
 11  TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)       8760 non-null   object
 12  TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)       8760 non-null   object
 13  UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)               8760 non-null   int64
 14  UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)               8760 non-null   int64
 15  UMIDADE RELATIVA DO AR, HORARIA (%)                    8760 non-null   int64
 16  VENTO, DIREÇÃO HORARIA (gr) (° (gr))                   8760 non-null   int64
 17  VENTO, RAJADA MAXIMA (m/s)                             8760 non-null   object
 18  VENTO, VELOCIDADE HORARIA (m/s)                        8760 non-null   object
 19  Unnamed: 19                                            0 non-null      float64
dtypes: float64(1), int64(5), object(14)
memory usage: 1.3+ MB

,DATA (YYYY-MM-DD),HORA (UTC),"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (KJ/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
0,2003-01-01,00:00,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,NaN
1,2003-01-01,01:00,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,NaN
2,2003-01-01,02:00,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,NaN
3,2003-01-01,03:00,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,NaN
4,2003-01-01,04:00,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,NaN

In [3]:
# estacao em 2013
estacao_ssa_2013.info()
estacao_ssa_2013.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 19 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   DATA (YYYY-MM-DD)                                      8760 non-null   object
 1   HORA (UTC)                                             8760 non-null   object
 2   PRECIPITAÇÃO TOTAL, HORÁRIO (mm)                       8760 non-null   object
 3   PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)  8760 non-null   object
 4   PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)        8760 non-null   object
 5   PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)       8760 non-null   object
 6   RADIACAO GLOBAL (KJ/m²)                                8760 non-null   object
 7   TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)           8760 non-null   object
 8   TEMPERATURA DO PONTO DE ORVALHO (°C)                   8760 non-null   object
 9   TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)             8760 non-null   object
 10  TEMPERATURA M�NIMA NA HORA ANT. (AUT) (�C)             8760 non-null   object
 11  TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)       8760 non-null   object
 12  TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)       8760 non-null   object
 13  UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)               8760 non-null   int64
 14  UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)               8760 non-null   int64
 15  UMIDADE RELATIVA DO AR, HORARIA (%)                    8760 non-null   int64
 16  VENTO, DIREÇÃO HORARIA (gr) (° (gr))                   8760 non-null   int64
 17  VENTO, RAJADA MAXIMA (m/s)                             8760 non-null   object
 18  VENTO, VELOCIDADE HORARIA (m/s)                        8760 non-null   object
dtypes: int64(4), object(15)
memory usage: 1.3+ MB

,DATA (YYYY-MM-DD),HORA (UTC),"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (KJ/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA M�NIMA NA HORA ANT. (AUT) (�C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)"
0,2013-01-01,00:00,0,"1008,3","1008,3",1008,-9999,"25,7",22,"25,8","25,5","22,1","21,6",80,78,80,97,"5,1","1,5"
1,2013-01-01,01:00,0,"1008,5","1008,5","1008,2",-9999,"25,8","21,9","25,9","25,4","22,1","21,6",80,79,79,96,"5,4","1,8"
2,2013-01-01,02:00,0,"1008,4","1008,5","1008,4",-9999,"25,3","21,9","25,8","25,1","21,9",21,81,78,81,103,"4,5","1,3"
3,2013-01-01,03:00,0,1008,"1008,4",1008,-9999,"25,3","21,5","25,5","25,2","21,9","21,4",81,79,80,85,"5,1","1,3"
4,2013-01-01,04:00,0,"1007,3",1008,"1007,3",-9999,"25,1","21,4","25,5","25,1","21,6","21,4",80,79,80,62,"5,5","1,1"

In [4]:
# estacao em 2023
estacao_ssa_2023.info()
estacao_ssa_2023.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 20 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   Data                                                   8760 non-null   object
 1   Hora UTC                                               8760 non-null   object
 2   PRECIPITAÇÃO TOTAL, HORÁRIO (mm)                       8756 non-null   object
 3   PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)  8756 non-null   object
 4   PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)        8756 non-null   object
 5   PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)       8756 non-null   object
 6   RADIACAO GLOBAL (Kj/m²)                                4735 non-null   object
 7   TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)           8756 non-null   object
 8   TEMPERATURA DO PONTO DE ORVALHO (°C)                   8756 non-null   object
 9   TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)             8756 non-null   object
 10  TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)             8756 non-null   object
 11  TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)       8756 non-null   object
 12  TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)       8756 non-null   object
 13  UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)               8756 non-null   float64
 14  UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)               8756 non-null   float64
 15  UMIDADE RELATIVA DO AR, HORARIA (%)                    8756 non-null   float64
 16  VENTO, DIREÇÃO HORARIA (gr) (° (gr))                   8756 non-null   float64
 17  VENTO, RAJADA MAXIMA (m/s)                             8756 non-null   object
 18  VENTO, VELOCIDADE HORARIA (m/s)                        8756 non-null   object
 19  Unnamed: 19                                            0 non-null      float64
dtypes: float64(5), object(15)
memory usage: 1.3+ MB

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
0,2023/01/01,0000 UTC,0,"1009,2","1009,2","1008,8",NaN,"26,2","21,8","26,3","26,1",22,"21,7",78.0,77.0,77.0,77.0,"4,7","1,3",NaN
1,2023/01/01,0100 UTC,0,"1009,4","1009,4","1009,2",NaN,"26,1",22,"26,3",26,22,"21,8",78.0,76.0,78.0,90.0,"4,7",1,NaN
2,2023/01/01,0200 UTC,0,"1009,1","1009,4","1009,1",NaN,26,22,"26,3",26,"22,3",22,79.0,78.0,79.0,79.0,5,",9",NaN
3,2023/01/01,0300 UTC,0,"1008,5","1009,1","1008,5",NaN,"25,8","21,9",26,"25,6","22,1","21,8",80.0,79.0,79.0,84.0,"4,8",1,NaN
4,2023/01/01,0400 UTC,"3,4","1008,1","1008,5","1008,1",NaN,"23,7","21,7","25,8","23,7","22,1","21,6",89.0,79.0,89.0,52.0,"4,6","1,4",NaN

* Limpando e unificando colunas para os três ``DataFrame``s.

In [5]:
# removendo colunas extraas
estacao_ssa_2003.drop(columns=['Unnamed: 19'], inplace=True)
estacao_ssa_2023.drop(columns=['Unnamed: 19'], inplace=True)

In [6]:
# unificando os dataframes
print("Colunas antes:")
colunas_2003 = estacao_ssa_2003.columns.values.tolist()
colunas_2013 = estacao_ssa_2013.columns.values.tolist()
colunas_2023 = estacao_ssa_2023.columns.values.tolist()

print(colunas_2003)
print(colunas_2013)
print(colunas_2023)

# renomeando colunas diferentes
print("\nColunas diferentes:")
for c_2003, c_2013, c_2023 in zip(colunas_2003, colunas_2013, colunas_2023):
    if c_2003 != c_2013 or c_2003 != c_2023:
        print(f"'{c_2003}' | '{c_2013}' | '{c_2023}'")
        estacao_ssa_2013.rename(columns={c_2013: c_2003}, inplace=True)
        estacao_ssa_2023.rename(columns={c_2023: c_2003}, inplace=True)


# imprimindo colunas depois
print("\nColunas depois:")
colunas_2003 = estacao_ssa_2003.columns.values.tolist()
colunas_2013 = estacao_ssa_2013.columns.values.tolist()
colunas_2023 = estacao_ssa_2023.columns.values.tolist()

print(colunas_2003)
print(colunas_2013)
print(colunas_2023)

Colunas antes:
['DATA (YYYY-MM-DD)', 'HORA (UTC)', 'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)', 'PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)', 'PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)', 'PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)', 'RADIACAO GLOBAL (KJ/m²)', 'TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)', 'TEMPERATURA DO PONTO DE ORVALHO (°C)', 'TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)', 'TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)', 'TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)', 'TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)', 'UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)', 'UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)', 'UMIDADE RELATIVA DO AR, HORARIA (%)', 'VENTO, DIREÇÃO HORARIA (gr) (° (gr))', 'VENTO, RAJADA MAXIMA (m/s)', 'VENTO, VELOCIDADE HORARIA (m/s)']
['DATA (YYYY-MM-DD)', 'HORA (UTC)', 'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)', 'PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)', 'PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)', 'PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)', 'RADIACAO GLOBAL (KJ/m²)', 'TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)', 'TEMPERATURA DO PONTO DE ORVALHO (°C)', 'TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)', 'TEMPERATURA M�NIMA NA HORA ANT. (AUT) (�C)', 'TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)', 'TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)', 'UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)', 'UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)', 'UMIDADE RELATIVA DO AR, HORARIA (%)', 'VENTO, DIREÇÃO HORARIA (gr) (° (gr))', 'VENTO, RAJADA MAXIMA (m/s)', 'VENTO, VELOCIDADE HORARIA (m/s)']
['Data', 'Hora UTC', 'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)', 'PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)', 'PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)', 'PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)', 'RADIACAO GLOBAL (Kj/m²)', 'TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)', 'TEMPERATURA DO PONTO DE ORVALHO (°C)', 'TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)', 'TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)', 'TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)', 'TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)', 'UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)', 'UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)', 'UMIDADE RELATIVA DO AR, HORARIA (%)', 'VENTO, DIREÇÃO HORARIA (gr) (° (gr))', 'VENTO, RAJADA MAXIMA (m/s)', 'VENTO, VELOCIDADE HORARIA (m/s)']

Colunas diferentes:
'DATA (YYYY-MM-DD)' | 'DATA (YYYY-MM-DD)' | 'Data'
'HORA (UTC)' | 'HORA (UTC)' | 'Hora UTC'
'RADIACAO GLOBAL (KJ/m²)' | 'RADIACAO GLOBAL (KJ/m²)' | 'RADIACAO GLOBAL (Kj/m²)'
'TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)' | 'TEMPERATURA M�NIMA NA HORA ANT. (AUT) (�C)' | 'TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)'

Colunas depois:
['DATA (YYYY-MM-DD)', 'HORA (UTC)', 'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)', 'PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)', 'PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)', 'PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)', 'RADIACAO GLOBAL (KJ/m²)', 'TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)', 'TEMPERATURA DO PONTO DE ORVALHO (°C)', 'TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)', 'TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)', 'TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)', 'TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)', 'UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)', 'UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)', 'UMIDADE RELATIVA DO AR, HORARIA (%)', 'VENTO, DIREÇÃO HORARIA (gr) (° (gr))', 'VENTO, RAJADA MAXIMA (m/s)', 'VENTO, VELOCIDADE HORARIA (m/s)']
['DATA (YYYY-MM-DD)', 'HORA (UTC)', 'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)', 'PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)', 'PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)', 'PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)', 'RADIACAO GLOBAL (KJ/m²)', 'TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)', 'TEMPERATURA DO PONTO DE ORVALHO (°C)', 'TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)', 'TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)', 'TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)', 'TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)', 'UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)', 'UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)', 'UMIDADE RELATIVA DO AR, HORARIA (%)', 'VENTO, DIREÇÃO HORARIA (gr) (° (gr))', 'VENTO, RAJADA MAXIMA (m/s)', 'VENTO, VELOCIDADE HORARIA (m/s)']
['DATA (YYYY-MM-DD)', 'HORA (UTC)', 'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)', 'PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)', 'PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)', 'PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)', 'RADIACAO GLOBAL (KJ/m²)', 'TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)', 'TEMPERATURA DO PONTO DE ORVALHO (°C)', 'TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)', 'TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)', 'TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)', 'TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)', 'UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)', 'UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)', 'UMIDADE RELATIVA DO AR, HORARIA (%)', 'VENTO, DIREÇÃO HORARIA (gr) (° (gr))', 'VENTO, RAJADA MAXIMA (m/s)', 'VENTO, VELOCIDADE HORARIA (m/s)']

### __Exercício 2: Juntando os datasets__

1. Constrindo um novo ``DataFrame`` utilizando um ``MultiIndex``.

In [7]:
# convertendo a coluna data para o tipo datetime
estacao_ssa_2003['DATA (YYYY-MM-DD)'] = pd.to_datetime(estacao_ssa_2003['DATA (YYYY-MM-DD)'])
estacao_ssa_2013['DATA (YYYY-MM-DD)'] = pd.to_datetime(estacao_ssa_2013['DATA (YYYY-MM-DD)'])
estacao_ssa_2023['DATA (YYYY-MM-DD)'] = pd.to_datetime(estacao_ssa_2023['DATA (YYYY-MM-DD)'])


# pegando listas com os anos, meses e dias de cada dataframe
anos = pd.concat([estacao_ssa_2003['DATA (YYYY-MM-DD)'].dt.year,
                  estacao_ssa_2013['DATA (YYYY-MM-DD)'].dt.year,
                  estacao_ssa_2023['DATA (YYYY-MM-DD)'].dt.year])
anos = anos.values

meses = pd.concat([estacao_ssa_2003['DATA (YYYY-MM-DD)'].dt.month,
                   estacao_ssa_2013['DATA (YYYY-MM-DD)'].dt.month,
                   estacao_ssa_2023['DATA (YYYY-MM-DD)'].dt.month])
meses = meses.values

dias = pd.concat([estacao_ssa_2003['DATA (YYYY-MM-DD)'].dt.day,
                  estacao_ssa_2013['DATA (YYYY-MM-DD)'].dt.day,
                  estacao_ssa_2023['DATA (YYYY-MM-DD)'].dt.day])



# criando indice
index = pd.MultiIndex.from_arrays([anos, meses, dias], names=['ano', 'mes', 'dia'])

In [8]:
# criando dataframa multiindexado por ano, mes e dia
estacoes_concat = pd.concat([estacao_ssa_2003, estacao_ssa_2013, estacao_ssa_2023])
estacao_ssa = estacoes_concat.drop(columns=['DATA (YYYY-MM-DD)', 'HORA (UTC)'])
estacao_ssa.set_index(index, inplace=True)
estacao_ssa

             PRECIPITAÇÃO TOTAL, HORÁRIO (mm)  \
ano  mes dia
2003 1   1                              -9999
         1                              -9999
         1                              -9999
         1                              -9999
         1                              -9999
...                                       ...
2023 12  31                                 0
         31                                 0
         31                                 0
         31                                 0
         31                                 0

             PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)  \
ano  mes dia
2003 1   1                                                -9999
         1                                                -9999
         1                                                -9999
         1                                                -9999
         1                                                -9999
...                                                         ...
2023 12  31                                              1004,6
         31                                              1004,8
         31                                                1005
         31                                              1005,3
         31                                              1005,8

             PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)  \
ano  mes dia
2003 1   1                                             -9999
         1                                             -9999
         1                                             -9999
         1                                             -9999
         1                                             -9999
...                                                      ...
2023 12  31                                           1005,1
         31                                           1004,8
         31                                           1005,1
         31                                           1005,3
         31                                           1005,8

             PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)  \
ano  mes dia
2003 1   1                                              -9999
         1                                              -9999
         1                                              -9999
         1                                              -9999
         1                                              -9999
...                                                       ...
2023 12  31                                            1004,6
         31                                            1004,5
         31                                            1004,8
         31                                            1004,9
         31                                            1005,3

             RADIACAO GLOBAL (KJ/m²)  \
ano  mes dia
2003 1   1                     -9999
         1                     -9999
         1                     -9999
         1                     -9999
         1                     -9999
...                              ...
2023 12  31                   1641,3
         31                    644,8
         31                    148,7
         31                      NaN
         31                      NaN

             TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)  \
ano  mes dia
2003 1   1                                          -9999
         1                                          -9999
         1                                          -9999
         1                                          -9999
         1                                          -9999
...                                                   ...
2023 12  31                                          29,9
         31                                          28,4
         31                                          27,3
         31                                            27
         31                                          26,7

             TEMPERATURA DO PONTO DE ORVALHO (°C)  \
ano  mes dia
2003 1   1                                  -9999
         1                                  -9999
         1                                  -9999
         1                                  -9999
         1                                  -9999
...                                           ...
2023 12  31                                  21,9
         31                                  21,9
         31                                  22,3
         31                                  22,3
         31                                  22,7

             TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)  \
ano  mes dia
2003 1   1                                        -9999
         1                                        -9999
         1                                        -9999
         1                                        -9999
         1                                        -9999
...                                                 ...
2023 12  31                                        30,9
         31                                        29,9
         31                                        28,4
         31                                        27,3
         31                                        27,1

             TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)  \
ano  mes dia
2003 1   1                                        -9999
         1                                        -9999
         1                                        -9999
         1                                        -9999
         1                                        -9999
...                                                 ...
2023 12  31                                        29,7
         31                                        28,4
         31                                        27,3
         31                                          27
         31                                        26,7

             TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)  \
ano  mes dia
2003 1   1                                              -9999
         1                                              -9999
         1                                              -9999
         1                                              -9999
         1                                              -9999
...                                                       ...
2023 12  31                                              23,1
         31                                              22,6
         31                                              22,4
         31                                              22,3
         31                                              22,7

             TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)  \
ano  mes dia
2003 1   1                                              -9999
         1                                              -9999
         1                                              -9999
         1                                              -9999
         1                                              -9999
...                                                       ...
2023 12  31                                              21,6
         31                                              21,8
         31                                              21,8
         31                                              22,1
         31                                              22,3

              UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)  \
ano  mes dia
2003 1   1                                     -9999.0
         1                                     -9999.0
         1                                     -9999.0
         1                                     -9999.0
         1                                     -9999.0
...                                                ...
2023 12  31                                       64.0
         31                                       69.0
         31                                       74.0
         31                                       75.0
         31                                       79.0

              UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)  \
ano  mes dia
2003 1   1                                     -9999.0
         1                                     -9999.0
         1                                     -9999.0
         1                                     -9999.0
         1                                     -9999.0
...                                                ...
2023 12  31                                       61.0
         31                                       62.0
         31                                       68.0
         31                                       73.0
         31                                       75.0

              UMIDADE RELATIVA DO AR, HORARIA (%)  \
ano  mes dia
2003 1   1                                -9999.0
         1                                -9999.0
         1                                -9999.0
         1                                -9999.0
         1                                -9999.0
...                                           ...
2023 12  31                                  62.0
         31                                  68.0
         31                                  74.0
         31                                  75.0
         31                                  78.0

              VENTO, DIREÇÃO HORARIA (gr) (° (gr)) VENTO, RAJADA MAXIMA (m/s)  \
ano  mes dia
2003 1   1                                 -9999.0                      -9999
         1                                 -9999.0                      -9999
         1                                 -9999.0                      -9999
         1                                 -9999.0                      -9999
         1                                 -9999.0                      -9999
...                                            ...                        ...
2023 12  31                                  106.0                        6,4
         31                                   91.0                        5,7
         31                                   80.0                        4,9
         31                                   65.0                        4,3
         31                                   74.0                        5,2

             VENTO, VELOCIDADE HORARIA (m/s)
ano  mes dia
2003 1   1                             -9999
         1                             -9999
         1                             -9999
         1                             -9999
         1                             -9999
...                                      ...
2023 12  31                              1,2
         31                              1,6
         31                              1,3
         31                                1
         31                              1,4

[26280 rows x 17 columns]

2. Construindo novo ``DataFrame`` utilizando ``MultiIndex`` como colunas contendo os parâmetros agrupados (precipitações, pressão, radiação, temperatura, umidade, velocidade do vento)

In [9]:
# criando multiindex para as colunas
nivel_1 = ['precipitacao'] + ['pressao']*3 + ['radiacao'] + ['temperatura']*6 + ['umidade']*3 + ['velocidade do vento']*3
nivel_2 = colunas_2003[2:]

# definindo multiindex para as colunas
index_col = pd.MultiIndex.from_arrays([nivel_1, nivel_2], names=['medicao', 'tipo'])

estacao_ssa.columns = index_col
estacao_ssa['HORA (UTC)'] = estacoes_concat['HORA (UTC)'].values # retornando a coluna hora
estacao_ssa

medicao                          precipitacao  \
tipo         PRECIPITAÇÃO TOTAL, HORÁRIO (mm)
ano  mes dia
2003 1   1                              -9999
         1                              -9999
         1                              -9999
         1                              -9999
         1                              -9999
...                                       ...
2023 12  31                                 0
         31                                 0
         31                                 0
         31                                 0
         31                                 0

medicao                                                    pressao  \
tipo         PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)
ano  mes dia
2003 1   1                                                -9999
         1                                                -9999
         1                                                -9999
         1                                                -9999
         1                                                -9999
...                                                         ...
2023 12  31                                              1004,6
         31                                              1004,8
         31                                                1005
         31                                              1005,3
         31                                              1005,8

medicao                                                       \
tipo         PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)
ano  mes dia
2003 1   1                                             -9999
         1                                             -9999
         1                                             -9999
         1                                             -9999
         1                                             -9999
...                                                      ...
2023 12  31                                           1005,1
         31                                           1004,8
         31                                           1005,1
         31                                           1005,3
         31                                           1005,8

medicao                                                        \
tipo         PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)
ano  mes dia
2003 1   1                                              -9999
         1                                              -9999
         1                                              -9999
         1                                              -9999
         1                                              -9999
...                                                       ...
2023 12  31                                            1004,6
         31                                            1004,5
         31                                            1004,8
         31                                            1004,9
         31                                            1005,3

medicao                     radiacao  \
tipo         RADIACAO GLOBAL (KJ/m²)
ano  mes dia
2003 1   1                     -9999
         1                     -9999
         1                     -9999
         1                     -9999
         1                     -9999
...                              ...
2023 12  31                   1641,3
         31                    644,8
         31                    148,7
         31                      NaN
         31                      NaN

medicao                                       temperatura  \
tipo         TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)
ano  mes dia
2003 1   1                                          -9999
         1                                          -9999
         1                                          -9999
         1                                          -9999
         1                                          -9999
...                                                   ...
2023 12  31                                          29,9
         31                                          28,4
         31                                          27,3
         31                                            27
         31                                          26,7

medicao                                            \
tipo         TEMPERATURA DO PONTO DE ORVALHO (°C)
ano  mes dia
2003 1   1                                  -9999
         1                                  -9999
         1                                  -9999
         1                                  -9999
         1                                  -9999
...                                           ...
2023 12  31                                  21,9
         31                                  21,9
         31                                  22,3
         31                                  22,3
         31                                  22,7

medicao                                                  \
tipo         TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)
ano  mes dia
2003 1   1                                        -9999
         1                                        -9999
         1                                        -9999
         1                                        -9999
         1                                        -9999
...                                                 ...
2023 12  31                                        30,9
         31                                        29,9
         31                                        28,4
         31                                        27,3
         31                                        27,1

medicao                                                  \
tipo         TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)
ano  mes dia
2003 1   1                                        -9999
         1                                        -9999
         1                                        -9999
         1                                        -9999
         1                                        -9999
...                                                 ...
2023 12  31                                        29,7
         31                                        28,4
         31                                        27,3
         31                                          27
         31                                        26,7

medicao                                                        \
tipo         TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)
ano  mes dia
2003 1   1                                              -9999
         1                                              -9999
         1                                              -9999
         1                                              -9999
         1                                              -9999
...                                                       ...
2023 12  31                                              23,1
         31                                              22,6
         31                                              22,4
         31                                              22,3
         31                                              22,7

medicao                                                        \
tipo         TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)
ano  mes dia
2003 1   1                                              -9999
         1                                              -9999
         1                                              -9999
         1                                              -9999
         1                                              -9999
...                                                       ...
2023 12  31                                              21,6
         31                                              21,8
         31                                              21,8
         31                                              22,1
         31                                              22,3

medicao                                       umidade  \
tipo         UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)
ano  mes dia
2003 1   1                                    -9999.0
         1                                    -9999.0
         1                                    -9999.0
         1                                    -9999.0
         1                                    -9999.0
...                                               ...
2023 12  31                                      64.0
         31                                      69.0
         31                                      74.0
         31                                      75.0
         31                                      79.0

medicao                                                \
tipo         UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)
ano  mes dia
2003 1   1                                    -9999.0
         1                                    -9999.0
         1                                    -9999.0
         1                                    -9999.0
         1                                    -9999.0
...                                               ...
2023 12  31                                      61.0
         31                                      62.0
         31                                      68.0
         31                                      73.0
         31                                      75.0

medicao                                           \
tipo         UMIDADE RELATIVA DO AR, HORARIA (%)
ano  mes dia
2003 1   1                               -9999.0
         1                               -9999.0
         1                               -9999.0
         1                               -9999.0
         1                               -9999.0
...                                          ...
2023 12  31                                 62.0
         31                                 68.0
         31                                 74.0
         31                                 75.0
         31                                 78.0

medicao                       velocidade do vento                             \
tipo         VENTO, DIREÇÃO HORARIA (gr) (° (gr)) VENTO, RAJADA MAXIMA (m/s)
ano  mes dia
2003 1   1                                -9999.0                      -9999
         1                                -9999.0                      -9999
         1                                -9999.0                      -9999
         1                                -9999.0                      -9999
         1                                -9999.0                      -9999
...                                           ...                        ...
2023 12  31                                 106.0                        6,4
         31                                  91.0                        5,7
         31                                  80.0                        4,9
         31                                  65.0                        4,3
         31                                  74.0                        5,2

medicao                                      HORA (UTC)
tipo         VENTO, VELOCIDADE HORARIA (m/s)
ano  mes dia
2003 1   1                             -9999      00:00
         1                             -9999      01:00
         1                             -9999      02:00
         1                             -9999      03:00
         1                             -9999      04:00
...                                      ...        ...
2023 12  31                              1,2   1900 UTC
         31                              1,6   2000 UTC
         31                              1,3   2100 UTC
         31                                1   2200 UTC
         31                              1,4   2300 UTC

[26280 rows x 18 columns]

### __Exercício 3: Analisando os DataFrame__

* Preparando os dados

In [10]:
import numpy as np
estacao_ssa.info()
estacao_ssa.head()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 26280 entries, (2003, 1, 1) to (2023, 12, 31)
Data columns (total 18 columns):
 #   Column                                                            Non-Null Count  Dtype
---  ------                                                            --------------  -----
 0   (precipitacao, PRECIPITAÇÃO TOTAL, HORÁRIO (mm))                  26276 non-null  object
 1   (pressao, PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB))  26276 non-null  object
 2   (pressao, PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB))        26276 non-null  object
 3   (pressao, PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB))       26276 non-null  object
 4   (radiacao, RADIACAO GLOBAL (KJ/m²))                               22255 non-null  object
 5   (temperatura, TEMPERATURA DO AR - BULBO SECO, HORARIA (°C))       26276 non-null  object
 6   (temperatura, TEMPERATURA DO PONTO DE ORVALHO (°C))               26276 non-null  object
 7   (temperatura, TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C))         26276 non-null  object
 8   (temperatura, TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C))         26276 non-null  object
 9   (temperatura, TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C))   26276 non-null  object
 10  (temperatura, TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C))   26276 non-null  object
 11  (umidade, UMIDADE REL. MAX. NA HORA ANT. (AUT) (%))               26276 non-null  float64
 12  (umidade, UMIDADE REL. MIN. NA HORA ANT. (AUT) (%))               26276 non-null  float64
 13  (umidade, UMIDADE RELATIVA DO AR, HORARIA (%))                    26276 non-null  float64
 14  (velocidade do vento, VENTO, DIREÇÃO HORARIA (gr) (° (gr)))       26276 non-null  float64
 15  (velocidade do vento, VENTO, RAJADA MAXIMA (m/s))                 26276 non-null  object
 16  (velocidade do vento, VENTO, VELOCIDADE HORARIA (m/s))            26276 non-null  object
 17  (HORA (UTC), )                                                    26280 non-null  object
dtypes: float64(4), object(14)
memory usage: 3.7+ MB

medicao                          precipitacao  \
tipo         PRECIPITAÇÃO TOTAL, HORÁRIO (mm)
ano  mes dia
2003 1   1                              -9999
         1                              -9999
         1                              -9999
         1                              -9999
         1                              -9999

medicao                                                    pressao  \
tipo         PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)
ano  mes dia
2003 1   1                                                -9999
         1                                                -9999
         1                                                -9999
         1                                                -9999
         1                                                -9999

medicao                                                       \
tipo         PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)
ano  mes dia
2003 1   1                                             -9999
         1                                             -9999
         1                                             -9999
         1                                             -9999
         1                                             -9999

medicao                                                        \
tipo         PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)
ano  mes dia
2003 1   1                                              -9999
         1                                              -9999
         1                                              -9999
         1                                              -9999
         1                                              -9999

medicao                     radiacao  \
tipo         RADIACAO GLOBAL (KJ/m²)
ano  mes dia
2003 1   1                     -9999
         1                     -9999
         1                     -9999
         1                     -9999
         1                     -9999

medicao                                       temperatura  \
tipo         TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)
ano  mes dia
2003 1   1                                          -9999
         1                                          -9999
         1                                          -9999
         1                                          -9999
         1                                          -9999

medicao                                            \
tipo         TEMPERATURA DO PONTO DE ORVALHO (°C)
ano  mes dia
2003 1   1                                  -9999
         1                                  -9999
         1                                  -9999
         1                                  -9999
         1                                  -9999

medicao                                                  \
tipo         TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)
ano  mes dia
2003 1   1                                        -9999
         1                                        -9999
         1                                        -9999
         1                                        -9999
         1                                        -9999

medicao                                                  \
tipo         TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)
ano  mes dia
2003 1   1                                        -9999
         1                                        -9999
         1                                        -9999
         1                                        -9999
         1                                        -9999

medicao                                                        \
tipo         TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)
ano  mes dia
2003 1   1                                              -9999
         1                                              -9999
         1                                              -9999
         1                                              -9999
         1                                              -9999

medicao                                                        \
tipo         TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)
ano  mes dia
2003 1   1                                              -9999
         1                                              -9999
         1                                              -9999
         1                                              -9999
         1                                              -9999

medicao                                       umidade  \
tipo         UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)
ano  mes dia
2003 1   1                                    -9999.0
         1                                    -9999.0
         1                                    -9999.0
         1                                    -9999.0
         1                                    -9999.0

medicao                                                \
tipo         UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)
ano  mes dia
2003 1   1                                    -9999.0
         1                                    -9999.0
         1                                    -9999.0
         1                                    -9999.0
         1                                    -9999.0

medicao                                           \
tipo         UMIDADE RELATIVA DO AR, HORARIA (%)
ano  mes dia
2003 1   1                               -9999.0
         1                               -9999.0
         1                               -9999.0
         1                               -9999.0
         1                               -9999.0

medicao                       velocidade do vento                             \
tipo         VENTO, DIREÇÃO HORARIA (gr) (° (gr)) VENTO, RAJADA MAXIMA (m/s)
ano  mes dia
2003 1   1                                -9999.0                      -9999
         1                                -9999.0                      -9999
         1                                -9999.0                      -9999
         1                                -9999.0                      -9999
         1                                -9999.0                      -9999

medicao                                      HORA (UTC)
tipo         VENTO, VELOCIDADE HORARIA (m/s)
ano  mes dia
2003 1   1                             -9999      00:00
         1                             -9999      01:00
         1                             -9999      02:00
         1                             -9999      03:00
         1                             -9999      04:00

In [11]:
# substituindo valores -9999 por NaN
estacao_ssa.replace(['-9999', -9999, -9999.0, '-9999.0'], value= np.nan, inplace=True)

estacao_ssa

medicao                          precipitacao  \
tipo         PRECIPITAÇÃO TOTAL, HORÁRIO (mm)
ano  mes dia
2003 1   1                                NaN
         1                                NaN
         1                                NaN
         1                                NaN
         1                                NaN
...                                       ...
2023 12  31                                 0
         31                                 0
         31                                 0
         31                                 0
         31                                 0

medicao                                                    pressao  \
tipo         PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)
ano  mes dia
2003 1   1                                                  NaN
         1                                                  NaN
         1                                                  NaN
         1                                                  NaN
         1                                                  NaN
...                                                         ...
2023 12  31                                              1004,6
         31                                              1004,8
         31                                                1005
         31                                              1005,3
         31                                              1005,8

medicao                                                       \
tipo         PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)
ano  mes dia
2003 1   1                                               NaN
         1                                               NaN
         1                                               NaN
         1                                               NaN
         1                                               NaN
...                                                      ...
2023 12  31                                           1005,1
         31                                           1004,8
         31                                           1005,1
         31                                           1005,3
         31                                           1005,8

medicao                                                        \
tipo         PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)
ano  mes dia
2003 1   1                                                NaN
         1                                                NaN
         1                                                NaN
         1                                                NaN
         1                                                NaN
...                                                       ...
2023 12  31                                            1004,6
         31                                            1004,5
         31                                            1004,8
         31                                            1004,9
         31                                            1005,3

medicao                     radiacao  \
tipo         RADIACAO GLOBAL (KJ/m²)
ano  mes dia
2003 1   1                       NaN
         1                       NaN
         1                       NaN
         1                       NaN
         1                       NaN
...                              ...
2023 12  31                   1641,3
         31                    644,8
         31                    148,7
         31                      NaN
         31                      NaN

medicao                                       temperatura  \
tipo         TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)
ano  mes dia
2003 1   1                                            NaN
         1                                            NaN
         1                                            NaN
         1                                            NaN
         1                                            NaN
...                                                   ...
2023 12  31                                          29,9
         31                                          28,4
         31                                          27,3
         31                                            27
         31                                          26,7

medicao                                            \
tipo         TEMPERATURA DO PONTO DE ORVALHO (°C)
ano  mes dia
2003 1   1                                    NaN
         1                                    NaN
         1                                    NaN
         1                                    NaN
         1                                    NaN
...                                           ...
2023 12  31                                  21,9
         31                                  21,9
         31                                  22,3
         31                                  22,3
         31                                  22,7

medicao                                                  \
tipo         TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)
ano  mes dia
2003 1   1                                          NaN
         1                                          NaN
         1                                          NaN
         1                                          NaN
         1                                          NaN
...                                                 ...
2023 12  31                                        30,9
         31                                        29,9
         31                                        28,4
         31                                        27,3
         31                                        27,1

medicao                                                  \
tipo         TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)
ano  mes dia
2003 1   1                                          NaN
         1                                          NaN
         1                                          NaN
         1                                          NaN
         1                                          NaN
...                                                 ...
2023 12  31                                        29,7
         31                                        28,4
         31                                        27,3
         31                                          27
         31                                        26,7

medicao                                                        \
tipo         TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)
ano  mes dia
2003 1   1                                                NaN
         1                                                NaN
         1                                                NaN
         1                                                NaN
         1                                                NaN
...                                                       ...
2023 12  31                                              23,1
         31                                              22,6
         31                                              22,4
         31                                              22,3
         31                                              22,7

medicao                                                        \
tipo         TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)
ano  mes dia
2003 1   1                                                NaN
         1                                                NaN
         1                                                NaN
         1                                                NaN
         1                                                NaN
...                                                       ...
2023 12  31                                              21,6
         31                                              21,8
         31                                              21,8
         31                                              22,1
         31                                              22,3

medicao                                       umidade  \
tipo         UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)
ano  mes dia
2003 1   1                                        NaN
         1                                        NaN
         1                                        NaN
         1                                        NaN
         1                                        NaN
...                                               ...
2023 12  31                                      64.0
         31                                      69.0
         31                                      74.0
         31                                      75.0
         31                                      79.0

medicao                                                \
tipo         UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)
ano  mes dia
2003 1   1                                        NaN
         1                                        NaN
         1                                        NaN
         1                                        NaN
         1                                        NaN
...                                               ...
2023 12  31                                      61.0
         31                                      62.0
         31                                      68.0
         31                                      73.0
         31                                      75.0

medicao                                           \
tipo         UMIDADE RELATIVA DO AR, HORARIA (%)
ano  mes dia
2003 1   1                                   NaN
         1                                   NaN
         1                                   NaN
         1                                   NaN
         1                                   NaN
...                                          ...
2023 12  31                                 62.0
         31                                 68.0
         31                                 74.0
         31                                 75.0
         31                                 78.0

medicao                       velocidade do vento                             \
tipo         VENTO, DIREÇÃO HORARIA (gr) (° (gr)) VENTO, RAJADA MAXIMA (m/s)
ano  mes dia
2003 1   1                                    NaN                        NaN
         1                                    NaN                        NaN
         1                                    NaN                        NaN
         1                                    NaN                        NaN
         1                                    NaN                        NaN
...                                           ...                        ...
2023 12  31                                 106.0                        6,4
         31                                  91.0                        5,7
         31                                  80.0                        4,9
         31                                  65.0                        4,3
         31                                  74.0                        5,2

medicao                                      HORA (UTC)
tipo         VENTO, VELOCIDADE HORARIA (m/s)
ano  mes dia
2003 1   1                               NaN      00:00
         1                               NaN      01:00
         1                               NaN      02:00
         1                               NaN      03:00
         1                               NaN      04:00
...                                      ...        ...
2023 12  31                              1,2   1900 UTC
         31                              1,6   2000 UTC
         31                              1,3   2100 UTC
         31                                1   2200 UTC
         31                              1,4   2300 UTC

[26280 rows x 18 columns]

In [12]:
# tratando precipitacao
print(estacao_ssa['precipitacao']['PRECIPITAÇÃO TOTAL, HORÁRIO (mm)'].unique())

# substiduindo valores , por .
estacao_ssa.loc[:, ('precipitacao', 'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)')].replace(',', '.', regex=True, inplace=True)

# convertendo para float
estacao_ssa['precipitacao'] = estacao_ssa['precipitacao'].astype('float64')

# preenchendo valores NaN com valor anteriores
estacao_ssa.loc[:, ('precipitacao', 'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)')].bfill(inplace=True)

[nan '0' ',2' '6' ',4' '4,8' '6,4' '1,4' '2,4' '1' ',6' '3' '21,8' '2,2'
 '6,8' ',8' '2,6' '4,6' '3,4' '8,4' '1,2' '1,8' '15,8' '12,4' '13,8' '4'
 '10,2' '2' '7,6' '1,6' '3,6' '3,2' '3,8' '4,2' '5,2' '5,8' '10,6' '6,2'
 '5,6' '9,6' '18,4' '7,4' '18' '16,2' '2,8' '5' '11,6' '10,4' '14,4' '52'
 '19' '24,4' '13' '21,6' '12,8' '17,6' '18,2' '11,8' '9' '9,4' '8,8' '22'
 '7,8' '8' '10' '11,2' '5,4' '12,2' '14,6' '7' '4,4' '12' '6,6' '15,2'
 '9,2' '13,2' '29,4' '7,2' '13,6' '0,8' '0,2' '0,4' '0,6' '9,8' '32,4'
 '20,6' '8,6' '16,6' '23,8' '14,2' '32,8' '12,6' '13,4' '11' '17' '15,6'
 '20,4' '17,2' '44,4' '16' '25' '16,8' '14' '8,2' '31,6' '24,2' '22,4'
 '16,4' '27,6' '38,4']

C:\Users\evera\AppData\Local\Temp\ipykernel_4592\3373811255.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  estacao_ssa.loc[:, ('precipitacao', 'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)')].replace(',', '.', regex=True, inplace=True)
C:\Users\evera\AppData\Local\Temp\ipykernel_4592\3373811255.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  estacao_ssa.loc[:, ('precipitacao', 'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)')].bfill(inplace=True)

In [13]:
# tratando temperaturas
print(np.unique(estacao_ssa['temperatura'].values.astype('str')))
colunas = estacao_ssa['temperatura'].columns.values.tolist()

# substiduindo valores , por .
for coluna in colunas:
    estacao_ssa.loc[:, ('temperatura', coluna)].replace(',', '.', regex=True, inplace=True)

# convertendo para float
estacao_ssa['temperatura'] = estacao_ssa['temperatura'].astype('float64')

# preenchendo valores NaN com valor anteriores
for coluna in colunas:
    estacao_ssa.loc[:, ('temperatura', coluna)].bfill(inplace=True)

['-1,8' '13,6' '14,2' '14,4' '14,6' '14,7' '14,8' '14,9' '15' '15,1'
 '15,2' '15,3' '15,4' '15,5' '15,6' '15,7' '15,8' '15,9' '16' '16,1'
 '16,2' '16,3' '16,4' '16,5' '16,6' '16,7' '16,8' '16,9' '17' '17,1'
 '17,2' '17,3' '17,4' '17,5' '17,6' '17,7' '17,8' '17,9' '18' '18,1'
 '18,2' '18,3' '18,4' '18,5' '18,6' '18,7' '18,8' '18,9' '19' '19,1'
 '19,2' '19,3' '19,4' '19,5' '19,6' '19,7' '19,8' '19,9' '20' '20,1'
 '20,2' '20,3' '20,4' '20,5' '20,6' '20,7' '20,8' '20,9' '21' '21,1'
 '21,2' '21,3' '21,4' '21,5' '21,6' '21,7' '21,8' '21,9' '22' '22,1'
 '22,2' '22,3' '22,4' '22,5' '22,6' '22,7' '22,8' '22,9' '23' '23,1'
 '23,2' '23,3' '23,4' '23,5' '23,6' '23,7' '23,8' '23,9' '24' '24,1'
 '24,2' '24,3' '24,4' '24,5' '24,6' '24,7' '24,8' '24,9' '25' '25,1'
 '25,2' '25,3' '25,4' '25,5' '25,6' '25,7' '25,8' '25,9' '26' '26,1'
 '26,2' '26,3' '26,4' '26,5' '26,6' '26,7' '26,8' '26,9' '27' '27,1'
 '27,2' '27,3' '27,4' '27,5' '27,6' '27,7' '27,8' '27,9' '28' '28,1'
 '28,2' '28,3' '28,4' '28,5' '28,6' '28,7' '28,8' '28,9' '29' '29,1'
 '29,2' '29,3' '29,4' '29,5' '29,6' '29,7' '29,8' '29,9' '30' '30,1'
 '30,2' '30,3' '30,4' '30,5' '30,6' '30,7' '30,8' '30,9' '31' '31,1'
 '31,2' '31,3' '31,4' '31,5' '31,6' '31,7' '31,8' '31,9' '32' '32,1'
 '32,2' '32,3' '32,4' '32,5' '32,6' '32,7' '32,8' '32,9' '33' '33,1'
 '33,2' '33,3' '33,4' '33,5' '33,6' '33,7' '33,8' '33,9' '34' '34,1'
 '34,2' '34,4' '34,6' '35,7' '36,7' '39,7' '41,6' '43,3' 'nan']

C:\Users\evera\AppData\Local\Temp\ipykernel_4592\2374666560.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  estacao_ssa.loc[:, ('temperatura', coluna)].replace(',', '.', regex=True, inplace=True)
C:\Users\evera\AppData\Local\Temp\ipykernel_4592\2374666560.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  estacao_ssa.loc[:, ('temperatura', coluna)].bfill(inplace=True)

In [14]:
# tratando hora

print(estacao_ssa['HORA (UTC)'].unique())
mask_utc = estacao_ssa['HORA (UTC)'].str.contains('UTC') 

# trantando dados utc
dados_utc = estacao_ssa.loc[mask_utc, 'HORA (UTC)']
dados_utc = dados_utc.replace(' UTC', '', regex=True) # removendo UTC
dados_utc = dados_utc.str[0:2] + ':00' # pegando apenas a hora

# colocando os dados tratados no dataframe
estacao_ssa.loc[mask_utc, 'HORA (UTC)'] = dados_utc.values
estacao_ssa['HORA (UTC)'].unique()

['00:00' '01:00' '02:00' '03:00' '04:00' '05:00' '06:00' '07:00' '08:00'
 '09:00' '10:00' '11:00' '12:00' '13:00' '14:00' '15:00' '16:00' '17:00'
 '18:00' '19:00' '20:00' '21:00' '22:00' '23:00' '0000 UTC' '0100 UTC'
 '0200 UTC' '0300 UTC' '0400 UTC' '0500 UTC' '0600 UTC' '0700 UTC'
 '0800 UTC' '0900 UTC' '1000 UTC' '1100 UTC' '1200 UTC' '1300 UTC'
 '1400 UTC' '1500 UTC' '1600 UTC' '1700 UTC' '1800 UTC' '1900 UTC'
 '2000 UTC' '2100 UTC' '2200 UTC' '2300 UTC']

array(['00:00', '01:00', '02:00', '03:00', '04:00', '05:00', '06:00',
       '07:00', '08:00', '09:00', '10:00', '11:00', '12:00', '13:00',
       '14:00', '15:00', '16:00', '17:00', '18:00', '19:00', '20:00',
       '21:00', '22:00', '23:00'], dtype=object)

1. Analisando as colunas relacionadas a precipitações e temperaturas.

In [15]:
# media de precipitacao por ano
precipitao_temp_ano = estacao_ssa[['precipitacao', 'temperatura']].groupby('ano')
precipitao_temp_ano.aggregate(['min', 'mean', 'max'])

medicao                     precipitacao                  \
tipo    PRECIPITAÇÃO TOTAL, HORÁRIO (mm)
                                     min      mean   max
ano
2003                                 0.0  0.232420  52.0
2013                                 0.0  0.201233  52.0
2023                                 0.0  0.174703  38.4

medicao                                  temperatura                   \
tipo    TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)
                                                 min       mean   max
ano
2003                                            20.3  25.889817  39.7
2013                                            19.5  25.677763  34.1
2023                                            20.5  26.034920  33.8

medicao                                                        \
tipo    TEMPERATURA DO PONTO DE ORVALHO (°C)
                                         min       mean   max
ano
2003                                    14.7  21.504703  26.6
2013                                    17.4  21.659897  26.0
2023                                    15.2  21.874703  26.2

medicao                                             ...        \
tipo    TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)  ...
                                               min  ...   max
ano                                                 ...
2003                                          20.7  ...  43.3
2013                                          20.1  ...  34.6
2023                                          20.7  ...  34.1

medicao                                                              \
tipo    TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)
                                               min       mean   max
ano
2003                                          20.2  25.426838  33.0
2013                                          19.3  25.195856  32.5
2023                                          20.5  25.558002  32.4

medicao                                                                    \
tipo    TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)
                                                     min       mean   max
ano
2003                                                15.3  22.000183  26.7
2013                                                18.0  22.098870  26.8
2023                                                16.2  22.332648  27.4

medicao
tipo    TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)
                                                     min       mean   max
ano
2003                                                13.6  21.115331  24.7
2013                                                -1.8  21.150080  24.5
2023                                                14.8  21.419315  25.1

[3 rows x 21 columns]

2. Comparando dados para o mes de Janeiro.

In [16]:
precipitao_temp_janeiro = estacao_ssa[['precipitacao', 'temperatura']].groupby(['ano', 'mes']).aggregate(['min', 'mean', 'max'])
precipitao_temp_janeiro.query('mes == 1')

medicao                      precipitacao                  \
tipo     PRECIPITAÇÃO TOTAL, HORÁRIO (mm)
                                      min      mean   max
ano  mes
2003 1                                0.0  0.000269   0.2
2013 1                                0.0  0.050000   5.8
2023 1                                0.0  0.167742  31.6

medicao                                   temperatura                   \
tipo     TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)
                                                  min       mean   max
ano  mes
2003 1                                           23.7  28.145296  32.0
2013 1                                           23.2  27.310215  34.1
2023 1                                           22.3  26.763038  31.5

medicao                                                         \
tipo     TEMPERATURA DO PONTO DE ORVALHO (°C)
                                          min       mean   max
ano  mes
2003 1                                   20.3  22.398253  23.7
2013 1                                   18.2  22.230376  25.3
2023 1                                   20.0  22.569892  26.2

medicao                                              ...        \
tipo     TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)  ...
                                                min  ...   max
ano  mes                                             ...
2003 1                                         23.8  ...  32.9
2013 1                                         23.4  ...  34.6
2023 1                                         22.7  ...  31.7

medicao                                                               \
tipo     TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)
                                                min       mean   max
ano  mes
2003 1                                         23.7  27.526882  31.6
2013 1                                         23.1  26.771909  32.3
2023 1                                         22.1  26.267608  30.7

medicao                                                                     \
tipo     TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)
                                                      min       mean   max
ano  mes
2003 1                                               21.5  23.119489  24.1
2013 1                                               20.0  22.676747  25.5
2023 1                                               20.7  23.051747  27.0

medicao
tipo     TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)
                                                      min       mean   max
ano  mes
2003 1                                               19.7  22.151747  23.6
2013 1                                               17.6  21.788441  24.3
2023 1                                               19.1  22.094355  24.3

[3 rows x 21 columns]

3. Comparando as informações sobre temperatura e precipitações medias em cada uma das estações dos três anos.

In [17]:
estacoes = {1: "verao", 2: "verao", 3:'verao', 
            4:'outono', 5:'outono', 6:'outono', 
            7:'inverno', 8:'inverno', 9:'inverno', 
            10:'primavera', 11:'primavera', 12:'primavera'}

precipitao_temp_estacao = estacao_ssa[['precipitacao', 'temperatura']].groupby(['mes']).mean().groupby(estacoes).mean()
precipitao_temp_estacao

medicao                       precipitacao  \
tipo      PRECIPITAÇÃO TOTAL, HORÁRIO (mm)
mes
inverno                           0.159919
outono                            0.384871
primavera                         0.147288
verao                             0.117352

medicao                                    temperatura  \
tipo      TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)
mes
inverno                                      24.199249
outono                                       25.577373
primavera                                    26.349559
verao                                        27.380827

medicao                                         \
tipo      TEMPERATURA DO PONTO DE ORVALHO (°C)
mes
inverno                              20.385250
outono                               22.158879
primavera                            21.689456
verao                                22.503655

medicao                                               \
tipo      TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)
mes
inverno                                    24.700257
outono                                     26.046526
primavera                                  26.855194
verao                                      27.916836

medicao                                               \
tipo      TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)
mes
inverno                                    23.782862
outono                                     25.120698
primavera                                  25.867377
verao                                      26.838725

medicao                                                     \
tipo      TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)
mes
inverno                                          20.805871
outono                                           22.618508
primavera                                        22.138339
verao                                            23.034294

medicao
tipo      TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)
mes
inverno                                          19.856201
outono                                           21.727805
primavera                                        21.272075
verao                                            22.076521

4. Comparando informações sobre temperatura e precipitações medias para o dia 28 de setembro  em cada um dos intervalos do dia dos três anos.

In [18]:
# vendo valores de hora
print(estacao_ssa['HORA (UTC)'].unique())

# criando diciionario para mapear as horas
horario = {'00:00': 'madrugada', '01:00': 'madrugada', '02:00': 'madrugada', '03:00': 'madrugada', '04:00': 'madrugada', '05:00': 'madrugada',
           '06:00': 'manha', '07:00': 'manha', '08:00': 'manha', '09:00': 'manha', '10:00': 'manha', '11:00': 'manha', '12:00': 'manha',
           '13:00': 'tarde', '14:00': 'tarde', '15:00': 'tarde', '16:00': 'tarde', '17:00': 'tarde', '18:00': 'tarde',
           '19:00': 'noite', '20:00': 'noite', '21:00': 'noite', '22:00': 'noite', '23:00': 'noite'}


# pegando dia 28 de setembro de cada ano
estacao_ssa_28_09 = estacao_ssa.query('mes == 9 and dia == 28')


# agrupando por hora
temp_hora = estacao_ssa_28_09.groupby('HORA (UTC)')['temperatura'].mean()
precipitacao_hora = estacao_ssa_28_09.groupby('HORA (UTC)')['precipitacao'].mean()

# concatenando os dataframes
precipitacao_temp_hora = pd.concat([precipitacao_hora, temp_hora], axis=1)
precipitacao_temp_hora

['00:00' '01:00' '02:00' '03:00' '04:00' '05:00' '06:00' '07:00' '08:00'
 '09:00' '10:00' '11:00' '12:00' '13:00' '14:00' '15:00' '16:00' '17:00'
 '18:00' '19:00' '20:00' '21:00' '22:00' '23:00']

medicao                        precipitacao  \
tipo       PRECIPITAÇÃO TOTAL, HORÁRIO (mm)
HORA (UTC)
00:00                                   0.0
01:00                                   0.0
02:00                                   0.0
03:00                                   0.0
04:00                                   0.0
05:00                                   0.0
06:00                                   0.0
07:00                                   0.0
08:00                                   0.0
09:00                                   0.0
10:00                                   0.0
11:00                                   0.0
12:00                                   0.0
13:00                                   0.0
14:00                                   0.0
15:00                                   0.0
16:00                                   0.0
17:00                                   0.0
18:00                                   0.0
19:00                                   0.0
20:00                                   0.0
21:00                                   0.0
22:00                                   0.0
23:00                                   0.0

medicao                                     temperatura  \
tipo       TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)
HORA (UTC)
00:00                                         24.600000
01:00                                         24.300000
02:00                                         24.200000
03:00                                         23.966667
04:00                                         23.733333
05:00                                         23.566667
06:00                                         23.366667
07:00                                         23.000000
08:00                                         22.966667
09:00                                         23.333333
10:00                                         24.933333
11:00                                         26.366667
12:00                                         28.000000
13:00                                         28.400000
14:00                                         28.766667
15:00                                         28.900000
16:00                                         28.666667
17:00                                         28.600000
18:00                                         27.866667
19:00                                         26.666667
20:00                                         25.333333
21:00                                         24.933333
22:00                                         24.700000
23:00                                         24.633333

medicao                                          \
tipo       TEMPERATURA DO PONTO DE ORVALHO (°C)
HORA (UTC)
00:00                                 20.700000
01:00                                 20.766667
02:00                                 20.966667
03:00                                 21.000000
04:00                                 20.866667
05:00                                 21.033333
06:00                                 20.833333
07:00                                 20.833333
08:00                                 20.900000
09:00                                 21.200000
10:00                                 21.400000
11:00                                 21.500000
12:00                                 21.500000
13:00                                 21.033333
14:00                                 21.300000
15:00                                 21.733333
16:00                                 21.733333
17:00                                 22.133333
18:00                                 21.466667
19:00                                 21.666667
20:00                                 21.566667
21:00                                 21.666667
22:00                                 21.500000
23:00                                 21.533333

medicao                                                \
tipo       TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)
HORA (UTC)
00:00                                       24.800000
01:00                                       24.600000
02:00                                       24.366667
03:00                                       24.233333
04:00                                       24.100000
05:00                                       23.800000
06:00                                       23.666667
07:00                                       23.433333
08:00                                       23.133333
09:00                                       23.333333
10:00                                       24.966667
11:00                                       26.500000
12:00                                       28.000000
13:00                                       28.866667
14:00                                       29.600000
15:00                                       29.466667
16:00                                       29.666667
17:00                                       29.300000
18:00                                       29.000000
19:00                                       27.900000
20:00                                       26.900000
21:00                                       25.400000
22:00                                       24.933333
23:00                                       24.700000

medicao                                                \
tipo       TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)
HORA (UTC)
00:00                                       24.433333
01:00                                       24.300000
02:00                                       24.033333
03:00                                       23.933333
04:00                                       23.700000
05:00                                       23.500000
06:00                                       23.366667
07:00                                       22.966667
08:00                                       22.900000
09:00                                       22.800000
10:00                                       23.333333
11:00                                       24.900000
12:00                                       26.033333
13:00                                       26.966667
14:00                                       28.000000
15:00                                       28.066667
16:00                                       28.333333
17:00                                       27.933333
18:00                                       27.733333
19:00                                       26.433333
20:00                                       25.300000
21:00                                       24.833333
22:00                                       24.700000
23:00                                       24.500000

medicao                                                      \
tipo       TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)
HORA (UTC)
00:00                                             20.800000
01:00                                             20.900000
02:00                                             21.000000
03:00                                             21.066667
04:00                                             21.233333
05:00                                             21.100000
06:00                                             21.133333
07:00                                             20.900000
08:00                                             21.000000
09:00                                             21.200000
10:00                                             21.800000
11:00                                             22.066667
12:00                                             22.033333
13:00                                             22.266667
14:00                                             22.300000
15:00                                             22.500000
16:00                                             22.600000
17:00                                             22.466667
18:00                                             22.533333
19:00                                             21.833333
20:00                                             21.833333
21:00                                             21.733333
22:00                                             21.833333
23:00                                             21.766667

medicao
tipo       TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)
HORA (UTC)
00:00                                             20.533333
01:00                                             20.633333
02:00                                             20.766667
03:00                                             20.800000
04:00                                             20.866667
05:00                                             20.766667
06:00                                             20.833333
07:00                                             20.600000
08:00                                             20.766667
09:00                                             20.733333
10:00                                             21.200000
11:00                                             21.066667
12:00                                             20.933333
13:00                                             20.733333
14:00                                             20.633333
15:00                                             20.666667
16:00                                             21.066667
17:00                                             21.266667
18:00                                             21.100000
19:00                                             21.100000
20:00                                             21.300000
21:00                                             21.500000
22:00                                             21.333333
23:00                                             21.333333

In [19]:
# agrupando por horario
precipitacao_temp_hora.groupby(horario).mean()

medicao                        precipitacao  \
tipo       PRECIPITAÇÃO TOTAL, HORÁRIO (mm)
HORA (UTC)
madrugada                               0.0
manha                                   0.0
noite                                   0.0
tarde                                   0.0

medicao                                     temperatura  \
tipo       TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)
HORA (UTC)
madrugada                                     24.061111
manha                                         24.566667
noite                                         25.253333
tarde                                         28.533333

medicao                                          \
tipo       TEMPERATURA DO PONTO DE ORVALHO (°C)
HORA (UTC)
madrugada                             20.888889
manha                                 21.166667
noite                                 21.586667
tarde                                 21.566667

medicao                                                \
tipo       TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)
HORA (UTC)
madrugada                                   24.316667
manha                                       24.719048
noite                                       25.966667
tarde                                       29.316667

medicao                                                \
tipo       TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)
HORA (UTC)
madrugada                                   23.983333
manha                                       23.757143
noite                                       25.153333
tarde                                       27.838889

medicao                                                      \
tipo       TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)
HORA (UTC)
madrugada                                         21.016667
manha                                             21.447619
noite                                             21.800000
tarde                                             22.444444

medicao
tipo       TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)
HORA (UTC)
madrugada                                         20.727778
manha                                             20.876190
noite                                             21.313333
tarde                                             20.911111